---
AllCops:
  TargetRubyVersion: 2.5
Naming/FileName:
  Enabled: false
Lint/MissingCopEnableDirective:
  Enabled: false
Lint/InterpolationCheck:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
