---
dist: trusty
group: beta
sudo: true
language: ruby
cache: bundler
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/htacg/tidy-html5/releases/download/5.2.0/tidy-5.2.0-64bit.deb; sudo apt-get remove '^libtidy.*';  sudo dpkg -i tidy-5.2.0-64bit.deb; fi
  - gem install bundler
rvm:
  - 2.1
  - 2.2
  - 2.3.4
  - 2.4.1
  - jruby-9.1.12.0
  - rbx-3
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - bundle exec rake
