sudo: false
bundler_args: --jobs=3 --retry=3
language: ruby
cache: bundler
before_install:
  - gem update --remote bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - jruby-9.1.5.0
  - rbx
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - bundle exec rake
