---
dist: trusty
group: beta
sudo: false
language: ruby
cache: bundler
before_install:
  - gem install bundler
rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.0
  - jruby-9.1.6.0
  - rbx-3
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - bundle exec rake
